Métodos Matemáticos Aplicados  EQE-703 1/2024    11/05/2024   J.Luiz <br>
Trabalho 1 : Matrizes, Sistemas Lineares, Formas Quadráticas, Autovetores e Autovalores <br>

In [1]:
import numpy as np
import pandas as pd
from src.functions import *

# Set the maximum number of columns to display
pd.set_option('display.max_columns', None)  # None means unlimited

Resposta Questão 1. Item (i):

In [2]:
A = np.array([[1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7, 8],
              [1, 3, 6, 10, 15, 21, 28, 36], [1, 4, 10, 20, 35, 56, 84, 120],
              [1, 5, 15, 35, 70, 126, 210, 330],
              [1, 6, 21, 56, 126, 252, 462, 792],
              [1, 7, 28, 84, 210, 462, 924, 1716],
              [1, 8, 36, 120, 330, 792, 1716, 3432]])
print('A = ' )
display_array_as_dataframe(A)

B = np.array([
    [11111],
    [22222],
    [33333],
    [44444],
    [44444],
    [33333],
    [22222],
    [11111]
])
print('B^T = ')
display_array_as_dataframe(B.T)

C = 10E5
print('C = ')
print(C)
print('\n')

E = np.array([[4, 0, 4, 0, -3, -4, 3, 1], [-2, -4, 2, 3, -2, 2, 0, -1],
              [1, 3, -3, -4, -3, 0, -2, 3], [0, 0, 0, -1, 1, 4, 1, 0],
              [3, 1, 4, 3, -2, 0, 3, 2], [2, 2, 4, -4, -3, 0, -4, 0]])

print('E = ')
display_array_as_dataframe(E)
print('\n')

A = 


0  1   2    3    4    5     6     7
0  1  1   1    1    1    1     1     1
1  1  2   3    4    5    6     7     8
2  1  3   6   10   15   21    28    36
3  1  4  10   20   35   56    84   120
4  1  5  15   35   70  126   210   330
5  1  6  21   56  126  252   462   792
6  1  7  28   84  210  462   924  1716
7  1  8  36  120  330  792  1716  3432

B^T = 


0      1      2      3      4      5      6      7
0  11111  22222  33333  44444  44444  33333  22222  11111

C = 
1000000.0


E = 


0  1  2  3  4  5  6  7
0  4  0  4  0 -3 -4  3  1
1 -2 -4  2  3 -2  2  0 -1
2  1  3 -3 -4 -3  0 -2  3
3  0  0  0 -1  1  4  1  0
4  3  1  4  3 -2  0  3  2
5  2  2  4 -4 -3  0 -4  0

In [3]:
P = schmidt_machine(A, A)
print('P = ')
display_array_as_dataframe(P)

P = 


0         1         2         3         4         5         6  \
0  0.353553 -0.621937  0.827579 -0.918925  0.700893 -0.350573  0.117650   
1  0.353553 -0.520175  0.489399 -0.124726 -0.483267  0.694842 -0.447862   
2  0.353553 -0.418413  0.227293  0.213274 -0.356596 -0.204861  0.612446   
3  0.353553 -0.316650  0.041262  0.238141  0.085604 -0.396740 -0.204580   
4  0.353553 -0.214888 -0.068693  0.092940  0.275758  0.124859 -0.354996   
5  0.353553 -0.113126 -0.102574 -0.079266  0.074012  0.325073  0.447010   
6  0.353553 -0.011363 -0.060380 -0.135411 -0.231764 -0.264725 -0.203941   
7  0.353553  0.090399  0.057889  0.067569  0.074024  0.059848  0.034687   

          7  
0 -0.024271  
1  0.151017  
2 -0.407745  
3  0.617795  
4 -0.566312  
5  0.313650  
6 -0.097082  
7  0.012944

Resposta Questão 1. Item (ii):

In [4]:
D = (P.T @ A) @ P
D = set_zero_if_below_tolerance(D)
print('D = ')
display_array_as_dataframe(D)

D = 


0          1         2         3        4         5         6  \
0  1608.625   0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   
1     0.000  27.437515  0.000000  0.000000  0.00000  0.000000  0.000000   
2     0.000   0.000000  3.871581  0.000000  0.00000  0.000000  0.000000   
3     0.000   0.000000  0.000000  1.523812  0.00000  0.000000  0.000000   
4     0.000   0.000000  0.000000  0.000000  0.48821  0.000000  0.000000   
5     0.000   0.000000  0.000000  0.000000  0.00000  0.081486  0.000000   
6     0.000   0.000000  0.000000  0.000000  0.00000  0.000000  0.006705   
7     0.000   0.000000  0.000000  0.000000  0.00000  0.000000  0.000000   

         7  
0  0.00000  
1  0.00000  
2  0.00000  
3  0.00000  
4  0.00000  
5  0.00000  
6  0.00000  
7  0.00022

Resposta Questão 1. Item (iii):

In [5]:
classify_diagonal(D)

'PD'

Resposta Questão 1. Item (iv):