Métodos Matemáticos Aplicados  EQE-703 1/2024    11/05/2024   J.Luiz <br>
Trabalho 1 : Matrizes, Sistemas Lineares, Formas Quadráticas, Autovetores e Autovalores <br> 
Questão 1 (6 Pontos; itens de igual valor) <br>

In [1]:
import numpy as np

(i) Desenvolver programa para aplicar o Processo Schmidt à matriz A de modo produzir a base 
 | P1 P2 P3 P4 P5 P6 P7 P8 | de vetores conjugados por A.

In [2]:
A = np.array([[1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7, 8],
              [1, 3, 6, 10, 15, 21, 28, 36], [1, 4, 10, 20, 35, 56, 84, 120],
              [1, 5, 15, 35, 70, 126, 210, 330],
              [1, 6, 21, 56, 126, 252, 462, 792],
              [1, 7, 28, 84, 210, 462, 924, 1716],
              [1, 8, 36, 120, 330, 792, 1716, 3432]])
print('A = ' )
print(A)
print('\n')

B = np.array([
    [11111],
    [22222],
    [33333],
    [44444],
    [44444],
    [33333],
    [22222],
    [11111]
])
print('B^T = ')
print(B.T)
print('\n')

C = 10E5
print('C = ')
print(C)
print('\n')

E = np.array([[4, 0, 4, 0, -3, -4, 3, 1], [-2, -4, 2, 3, -2, 2, 0, -1],
              [1, 3, -3, -4, -3, 0, -2, 3], [0, 0, 0, -1, 1, 4, 1, 0],
              [3, 1, 4, 3, -2, 0, 3, 2], [2, 2, 4, -4, -3, 0, -4, 0]])

print('E = ')
print(E)
print('\n')

A = 
[[   1    1    1    1    1    1    1    1]
 [   1    2    3    4    5    6    7    8]
 [   1    3    6   10   15   21   28   36]
 [   1    4   10   20   35   56   84  120]
 [   1    5   15   35   70  126  210  330]
 [   1    6   21   56  126  252  462  792]
 [   1    7   28   84  210  462  924 1716]
 [   1    8   36  120  330  792 1716 3432]]


B^T = 
[[11111 22222 33333 44444 44444 33333 22222 11111]]


C = 
1000000.0


E = 
[[ 4  0  4  0 -3 -4  3  1]
 [-2 -4  2  3 -2  2  0 -1]
 [ 1  3 -3 -4 -3  0 -2  3]
 [ 0  0  0 -1  1  4  1  0]
 [ 3  1  4  3 -2  0  3  2]
 [ 2  2  4 -4 -3  0 -4  0]]




In [3]:
def schmidt_machine(W):
    """Applies the Schmidt process to matrix A to orthogonalize its columns vectors."""

    # Grant elements as float
    W = W.astype(float)

    # Number of vectors (columns)
    n = W.shape[1]

    # Initialize the orthogonal matrix with zeros
    P = np.zeros_like(W)

    # Make P0 = W0
    P0 = W[:, 0]
    P[:, 0] = P0

    # Loop to calculate P1, P2, ..., Pn-1
    for k in range(1, n):
        # Start with Wk
        Pk = W[:, k]

        # Subtract the projections of Wk onto all previous Pi (i < k)
        for i in range(k):
            Pi = P[:, i]
            Wk = W[:, k]
            alpha = -(Pi.T @ Wk) / (Pi.T @ Pi)
            Pk += alpha * Pi

        # Set the calculated Pi into the ith column of P
        P[:, k] = Pk

    for i in range(P.shape[1]):  # Iterate over columns
        vector = P[:, i]
        norm = np.linalg.norm(vector)
        if norm != 0:
            P[:, i] = vector / norm

    return P

In [4]:
P = schmidt_machine(A)
print('P = ')
print(P)

P = 
[[ 0.35355339 -0.54006172  0.54006172 -0.43082022  0.28203804 -0.14978617
   0.06154575 -0.01706972]
 [ 0.35355339 -0.38575837  0.07715167  0.30772873 -0.52378493  0.49215457
  -0.30772873  0.11948803]
 [ 0.35355339 -0.23145502 -0.23145502  0.43082022 -0.12087344 -0.36376642
   0.55391171 -0.35846409]
 [ 0.35355339 -0.07715167 -0.38575837  0.18463724  0.36262033 -0.32097037
  -0.30772873  0.59744015]
 [ 0.35355339  0.07715167 -0.38575837 -0.18463724  0.36262033  0.32097037
  -0.30772873 -0.59744015]
 [ 0.35355339  0.23145502 -0.23145502 -0.43082022 -0.12087344  0.36376642
   0.55391171  0.35846409]
 [ 0.35355339  0.38575837  0.07715167 -0.30772873 -0.52378493 -0.49215457
  -0.30772873 -0.11948803]
 [ 0.35355339  0.54006172  0.54006172  0.43082022  0.28203804  0.14978617
   0.06154575  0.01706972]]


In [5]:
def are_columns_orthogonal(matrix, tolerance=1e-10):
    """
    Checks if the columns of the given matrix are orthogonal to each other within a specified tolerance.

    Parameters:
    matrix (numpy.ndarray): A 2D NumPy array where each column is a vector.
    tolerance (float): The tolerance within which the dot product is considered zero.

    Returns:
    bool: True if all columns are orthogonal to each other within the specified tolerance, False otherwise.
    """
    num_columns = matrix.shape[1]

    for i in range(num_columns):
        for j in range(i + 1, num_columns):
            dot_product = np.dot(matrix[:, i], matrix[:, j])
            if abs(dot_product) > tolerance:
                print(f"Columns {i} and {j} are not orthogonal. Dot product: {dot_product}")
                return False
            else:
                print(f"Columns {i} and {j} are orthogonal within tolerance. Dot product: {dot_product}")

    return True

In [6]:
print(are_columns_orthogonal(P))

Columns 0 and 1 are orthogonal within tolerance. Dot product: 0.0
Columns 0 and 2 are orthogonal within tolerance. Dot product: -5.551115123125783e-17
Columns 0 and 3 are orthogonal within tolerance. Dot product: 0.0
Columns 0 and 4 are orthogonal within tolerance. Dot product: 7.216449660063518e-16
Columns 0 and 5 are orthogonal within tolerance. Dot product: -1.4710455076283324e-14
Columns 0 and 6 are orthogonal within tolerance. Dot product: 6.628031457012185e-14
Columns 0 and 7 are orthogonal within tolerance. Dot product: 4.765243755144866e-12
Columns 1 and 2 are orthogonal within tolerance. Dot product: 0.0
Columns 1 and 3 are orthogonal within tolerance. Dot product: -5.551115123125783e-17
Columns 1 and 4 are orthogonal within tolerance. Dot product: 0.0
Columns 1 and 5 are orthogonal within tolerance. Dot product: 2.5646151868841116e-14
Columns 1 and 6 are orthogonal within tolerance. Dot product: -8.148481889236336e-13
Columns 1 and 7 are orthogonal within tolerance. Dot produ

In [7]:
D = (P.T @ A) @ P
print(D.shape)
print(D)

(8, 8)
[[1.60862500e+03 1.83354855e+03 1.02155978e+03 3.36209233e+02
  6.56270470e+01 7.13411954e+00 3.69915017e-01 6.03515374e-03]
 [1.83354855e+03 2.15300595e+03 1.25557738e+03 4.34593407e+02
  8.90811319e+01 1.01249295e+01 5.46061093e-01 9.21881635e-03]
 [1.02155978e+03 1.25557738e+03 7.96458333e+02 3.05267146e+02
  6.93481862e+01 8.66553967e+00 5.08074235e-01 9.21876961e-03]
 [3.36209233e+02 4.34593407e+02 3.05267146e+02 1.35852273e+02
  3.64547864e+01 5.33762825e+00 3.59848484e-01 7.35400382e-03]
 [6.56270470e+01 8.90811319e+01 6.93481862e+01 3.64547864e+01
  1.23977273e+01 2.32866980e+00 1.95900151e-01 4.81431490e-03]
 [7.13411954e+00 1.01249295e+01 8.66553967e+00 5.33762825e+00
  2.32866980e+00 6.41483516e-01 7.77004853e-02 2.55680838e-03]
 [3.69915017e-01 5.46061093e-01 5.08074235e-01 3.59848484e-01
  1.95900151e-01 7.77004853e-02 1.89393939e-02 1.05056858e-03]
 [6.03515374e-03 9.21881635e-03 9.21876961e-03 7.35400382e-03
  4.81431490e-03 2.55680838e-03 1.05056858e-03 2.9137529