Métodos Matemáticos Aplicados  EQE-703 1/2024    11/05/2024   J.Luiz <br>
Trabalho 1 : Matrizes, Sistemas Lineares, Formas Quadráticas, Autovetores e Autovalores <br> 
Questão 1 (6 Pontos; itens de igual valor) <br>

In [1]:
import numpy as np
from functions import *

(i) Desenvolver programa para aplicar o Processo Schmidt à matriz A de modo produzir a base 
 | P1 P2 P3 P4 P5 P6 P7 P8 | de vetores conjugados por A.

In [2]:
A = np.array([[1, 1, 1, 1, 1, 1, 1, 1], [1, 2, 3, 4, 5, 6, 7, 8],
              [1, 3, 6, 10, 15, 21, 28, 36], [1, 4, 10, 20, 35, 56, 84, 120],
              [1, 5, 15, 35, 70, 126, 210, 330],
              [1, 6, 21, 56, 126, 252, 462, 792],
              [1, 7, 28, 84, 210, 462, 924, 1716],
              [1, 8, 36, 120, 330, 792, 1716, 3432]])
print('A = ' )
print(A)
print('\n')

B = np.array([
    [11111],
    [22222],
    [33333],
    [44444],
    [44444],
    [33333],
    [22222],
    [11111]
])
print('B^T = ')
print(B.T)
print('\n')

C = 10E5
print('C = ')
print(C)
print('\n')

E = np.array([[4, 0, 4, 0, -3, -4, 3, 1], [-2, -4, 2, 3, -2, 2, 0, -1],
              [1, 3, -3, -4, -3, 0, -2, 3], [0, 0, 0, -1, 1, 4, 1, 0],
              [3, 1, 4, 3, -2, 0, 3, 2], [2, 2, 4, -4, -3, 0, -4, 0]])

print('E = ')
print(E)
print('\n')

A = 
[[   1    1    1    1    1    1    1    1]
 [   1    2    3    4    5    6    7    8]
 [   1    3    6   10   15   21   28   36]
 [   1    4   10   20   35   56   84  120]
 [   1    5   15   35   70  126  210  330]
 [   1    6   21   56  126  252  462  792]
 [   1    7   28   84  210  462  924 1716]
 [   1    8   36  120  330  792 1716 3432]]


B^T = 
[[11111 22222 33333 44444 44444 33333 22222 11111]]


C = 
1000000.0


E = 
[[ 4  0  4  0 -3 -4  3  1]
 [-2 -4  2  3 -2  2  0 -1]
 [ 1  3 -3 -4 -3  0 -2  3]
 [ 0  0  0 -1  1  4  1  0]
 [ 3  1  4  3 -2  0  3  2]
 [ 2  2  4 -4 -3  0 -4  0]]




In [4]:
P = schmidt_machine(A, A)
print('P = ')
print(P)

P = 
[[ 0.35355339 -0.62193738  0.82757909 -0.91892515  0.70089268 -0.35057265
   0.11764968 -0.02427052]
 [ 0.35355339 -0.52017501  0.48939864 -0.12472633 -0.48326652  0.69484195
  -0.44786158  0.15101659]
 [ 0.35355339 -0.41841264  0.22729309  0.2132743  -0.35659638 -0.20486057
   0.61244641 -0.4077448 ]
 [ 0.35355339 -0.31665027  0.04126246  0.23814143  0.08560376 -0.3967401
  -0.20457958  0.61779516]
 [ 0.35355339 -0.2148879  -0.06869327  0.09293975  0.27575758  0.1248594
  -0.35499586 -0.56631223]
 [ 0.35355339 -0.11312553 -0.10257409 -0.07926603  0.0740118   0.32507257
   0.44701024  0.31364985]
 [ 0.35355339 -0.01136316 -0.06038001 -0.13541123 -0.2317638  -0.26472465
  -0.20394052 -0.0970821 ]
 [ 0.35355339  0.09039921  0.05788899  0.06756885  0.0740236   0.05984764
   0.03468695  0.01294428]]


In [6]:
print(are_columns_orthogonal(P))

Columns 0 and 1 are not orthogonal. Dot product: -0.7517084869962198
False


In [7]:
D = (P.T @ A) @ P
print(D.shape)
print(D)

(8, 8)
[[ 1.60862500e+03  4.91954329e-14 -3.55249044e-13  4.34750406e-12
  -6.31846266e-11  4.44035413e-10  5.35763142e-09 -2.88090239e-07]
 [ 2.98366470e-14  2.74375154e+01 -1.49515318e-14  1.91319176e-13
  -3.65021731e-12  5.39642666e-11 -5.08904889e-10  1.92022115e-09]
 [-3.71729570e-13 -1.53505596e-14  3.87158134e+00  4.09393958e-15
  -1.17136486e-14 -8.11795665e-13  3.18962261e-11 -1.07253660e-09]
 [ 4.34512196e-12  1.91512781e-13  4.38403969e-15  1.52381160e+00
   1.55625983e-16  3.77933268e-14 -1.25422078e-12  3.69524482e-11]
 [-6.31581877e-11 -3.65371438e-12 -1.12049374e-14 -9.77150883e-16
   4.88209673e-01  8.11021001e-15 -1.47427250e-14 -1.15047350e-13]
 [ 4.44081458e-10  5.39622164e-11 -8.13878622e-13  3.40183237e-14
   2.71778500e-15  8.14861948e-02 -6.03064869e-16 -2.01345715e-14]
 [ 5.35769914e-09 -5.08905916e-10  3.18949349e-11 -1.25276878e-12
  -1.36275022e-14  5.59827374e-15  6.70465366e-03 -8.63650384e-17]
 [-2.88090205e-07  1.92021519e-09 -1.07253857e-09  3.69514243e